// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4G7ZUNGgEvzlTIQB_kIcqgAWa24MBRDw',
    appId: '1:253301128149:web:d8a738acd8bea64a685b5c',
    messagingSenderId: '253301128149',
    projectId: 'sproutsave-garden-app',
    authDomain: 'sproutsave-garden-app.firebaseapp.com',
    storageBucket: 'sproutsave-garden-app.appspot.com',
    measurementId: 'G-WH4EFN8YXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOOzC_xhnzD7HC2y70Wk6WkACniLcMsI',
    appId: '1:253301128149:android:36633323b26d1bdc685b5c',
    messagingSenderId: '253301128149',
    projectId: 'sproutsave-garden-app',
    storageBucket: 'sproutsave-garden-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwisCl_4fd7Hs2hqNZn1_mtl091crfam8',
    appId: '1:253301128149:ios:963f3a86e562707a685b5c',
    messagingSenderId: '253301128149',
    projectId: 'sproutsave-garden-app',
    storageBucket: 'sproutsave-garden-app.appspot.com',
    iosBundleId: 'com.sproutsave.gardenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwisCl_4fd7Hs2hqNZn1_mtl091crfam8',
    appId: '1:253301128149:ios:963f3a86e562707a685b5c',
    messagingSenderId: '253301128149',
    projectId: 'sproutsave-garden-app',
    storageBucket: 'sproutsave-garden-app.appspot.com',
    iosBundleId: 'com.sproutsave.gardenapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4G7ZUNGgEvzlTIQB_kIcqgAWa24MBRDw',
    appId: '1:253301128149:web:f5afc3da15fe8ccd685b5c',
    messagingSenderId: '253301128149',
    projectId: 'sproutsave-garden-app',
    authDomain: 'sproutsave-garden-app.firebaseapp.com',
    storageBucket: 'sproutsave-garden-app.appspot.com',
    measurementId: 'G-71NYLMZHSF',
  );
}
